services:

  # =====================================================
  # FRONTEND
  # =====================================================

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: wedding-frontend

    restart: unless-stopped

    ports:
      - "5173:5173"

    depends_on:
      - backend

    networks:
      - wedding


  # =====================================================
  # BACKEND
  # =====================================================

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: wedding-backend

    restart: unless-stopped

    env_file:
      - compose.env

    ports:
      - "8080:8080"

    volumes:
      # Fotos y perfiles
      - ./data/wedding:/data/wedding

    depends_on:
      database:
        condition: service_healthy

    networks:
      - wedding


  # =====================================================
  # DATABASE
  # =====================================================

  database:
    image: postgres:17

    container_name: wedding-database

    restart: unless-stopped

    env_file:
      - compose.env

    ports:
      - "5432:5432"

    volumes:
      # Persistencia de PostgreSQL
      # - ./data/postgres:/var/lib/postgresql/data

      # Scripts iniciales
      - ./database/init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - wedding


# =====================================================
# NETWORK
# =====================================================

networks:
  wedding:
    driver: bridge